import type { Question } from "./types";

export const questions36: Question[] = [
  {
    id: "Q1",
    scene: "TEAM",
    kind: "ACTION",
    text: "你负责的任务突然提前deadline，时间少一半。你第一反应是：",
    options: [
      { key: "A", text: "立刻拆任务、列清单，把能并行的全部并行", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "先找关键人确认底线：哪些必须做、哪些能砍", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "马上调动资源：找人支援、借工具、换方案", score: [{ agent: "TR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "先发一个简短通知，统一大家节奏和口径", score: [{ agent: "BR", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q2",
    scene: "INT",
    kind: "FRICTION",
    text: "你想沟通一个问题，对方说：我现在不想聊，冷静一下。你更可能先：",
    options: [
      { key: "A", text: "把沟通变成预约：我需要一个回来的时间点", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "先问一句：你现在更希望我陪着，还是先退开", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "先确认底线：你可以冷静，但你不是要消失对吗", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "先丢一句轻松的话缓和，等气氛回来了再切入", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
    ],
  },
  {
    id: "Q3",
    scene: "SOC",
    kind: "ACTION",
    text: "饭局/聚会气氛突然冷下来，你通常会：",
    options: [
      { key: "A", text: "抛一个轻松话题，让大家都能接", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "B", text: "点名夸一个人，把他推到台前发光", score: [{ agent: "BI", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "C", text: "转向聊最近大家都关心的热点，把局拉动", score: [{ agent: "BR", weight: 2 }, { agent: "TR", weight: 1 }] },
      { key: "D", text: "找一个人私聊两句，先把一个点燃起来", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
    ],
  },
  {
    id: "Q4",
    scene: "TEAM",
    kind: "ALLOC",
    text: "如果预算/资源只够押一个方向，你更倾向押：",
    options: [
      { key: "A", text: "短期可交付、可验证的成果", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "能撬动后续资源与机会的方向", score: [{ agent: "TR", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "C", text: "能提升掌控力的流程/工具/制度", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "D", text: "能对外出圈、形成案例的曝光", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
    ],
  },
  {
    id: "Q5",
    scene: "INT",
    kind: "ACTION",
    text: "你很累，但对方情绪上来开始闹。你更可能：",
    options: [
      { key: "A", text: "先抱一抱/陪一会儿，别讲道理", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "B", text: "讲事实：我没电了，我需要时间恢复", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "先用一个小动作满足TA，然后我去休息", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "拆关键点：我们到底在吵什么，最快解决", score: [{ agent: "BU", weight: 2 }, { agent: "TR", weight: 1 }] },
    ],
  },
  {
    id: "Q6",
    scene: "SOC",
    kind: "THREAT",
    text: "你在公共场合被开玩笑弄得有点难堪，你会：",
    options: [
      { key: "A", text: "幽默反击一下，把场子拿回来", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "B", text: "直接表态：这个玩笑过界了", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "C", text: "不接茬，转移话题，避免升级", score: [{ agent: "BR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "记下来：用结果/场面让他以后闭嘴", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
    ],
  },
  {
    id: "Q7",
    scene: "TEAM",
    kind: "FRICTION",
    text: "团队里有人长期拖延影响全局，你更可能：",
    options: [
      { key: "A", text: "设规则/节点/代价，按机制跑", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "私下沟通，帮他拆解到能做的程度", score: [{ agent: "BI", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "调整分工：关键任务收回来或换人", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "公开复盘，让拖延变成压力", score: [{ agent: "BR", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q8",
    scene: "INT",
    kind: "ACTION",
    text: "争执刚发生的前3分钟，你更可能先做哪一步？",
    options: [
      { key: "A", text: "先把关系抱回来：我不想我们现在伤到彼此", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "B", text: "先把边界放出来：有些话/有些事不能这样", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "C", text: "先把问题拆出来：我们到底在吵哪一个点", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "先把体面保住：不在当下做伤人的决定", score: [{ agent: "BR", weight: 2 }, { agent: "BI", weight: 1 }] },
    ],
  },
  {
    id: "Q9",
    scene: "SOC",
    kind: "ACTION",
    text: "初次自我介绍，你更可能：",
    options: [
      { key: "A", text: "一句话给出记忆点，让人记住你", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "B", text: "说清你能提供的价值/资源/合作方向", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "先问对方：你现在最关心什么？找共同点", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "D", text: "低调一点：留到后面用事实证明自己", score: [{ agent: "BU", weight: 2 }, { agent: "HU", weight: 1 }] },
    ],
  },
  {
    id: "Q10",
    scene: "TEAM",
    kind: "THREAT",
    text: "你发现功劳被模糊/被抢，你会：",
    options: [
      { key: "A", text: "当场补上关键事实，把贡献讲清楚", score: [{ agent: "BR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "私下对齐：以后必须明确标注与口径", score: [{ agent: "CM", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "不争一时：下次成果做大，让他抢不了", score: [{ agent: "BU", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "D", text: "直接指出谁在模糊事实，让他停", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q11",
    scene: "INT",
    kind: "ACTION",
    text: "你想确认一件事，但又怕显得压迫，你会：",
    options: [
      { key: "A", text: "轻松试探一下，给对方台阶", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "B", text: "直接问清楚：我需要一个明确答案", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "提一个具体请求：你能不能做到X？", score: [{ agent: "BU", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "先观察：用事实来判断，而不是逼问", score: [{ agent: "HU", weight: 2 }, { agent: "TR", weight: 1 }] },
    ],
  },
  {
    id: "Q12",
    scene: "SOC",
    kind: "ACTION",
    text: "你想在一个新圈子里更快被记住，你更可能先做哪件事？",
    options: [
      { key: "A", text: "输出一个让人记住的观点/内容", score: [{ agent: "BR", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "先让大家舒服：稳定出现、照顾链接", score: [{ agent: "BI", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "先帮人解决问题：提供资源/机会/信息", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "先把个人气质做出来：氛围与辨识度", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
    ],
  },
  {
    id: "Q13",
    scene: "INT",
    kind: "THREAT",
    text: "对方突然几个小时不回，你发现自己开始胡思乱想。你更可能：",
    options: [
      { key: "A", text: "先做自己的事，等对方回来再说", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "发一句轻松的话试探一下，别把气氛搞僵", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "C", text: "直接要一个时间点：你能不能给个回归时间？", score: [{ agent: "CM", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "先把最坏情况想清楚：如果一直这样我怎么应对", score: [{ agent: "HU", weight: 2 }, { agent: "TR", weight: 1 }] },
    ],
  },
  {
    id: "Q14",
    scene: "TEAM",
    kind: "THREAT",
    text: "项目关键成员临时反悔，说我不做了。你第一反应：",
    options: [
      { key: "A", text: "立刻找替代方案，把关键路径补上", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "先谈条件：你需要什么？我能给什么？", score: [{ agent: "TR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "当场定规则：这是承诺问题，不允许临时掀桌", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "D", text: "先稳住全队情绪，避免恐慌扩散", score: [{ agent: "BI", weight: 2 }, { agent: "BR", weight: 1 }] },
    ],
  },
  {
    id: "Q15",
    scene: "SOC",
    kind: "ALLOC",
    text: "你有机会带一个人去高质量社交局，你更愿意带：",
    options: [
      { key: "A", text: "能一起输出观点、帮你控场的人", score: [{ agent: "BR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "情商高、能帮你润滑关系的人", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "有资源/能带来后续合作的人", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "你信得过、不会让你尴尬的人", score: [{ agent: "BI", weight: 2 }, { agent: "BU", weight: 1 }] },
    ],
  },
  {
    id: "Q16",
    scene: "INT",
    kind: "ALLOC",
    text: "当你不安时，你更想从对方那里得到哪种确定感？",
    options: [
      { key: "A", text: "一个明确时间点：什么时候再聊/什么时候见", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "一个明确态度：你是不是还在乎我", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "一个明确行动：先做到一件小事证明", score: [{ agent: "BU", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "D", text: "一个明确解释：到底怎么回事/原因是什么", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q17",
    scene: "TEAM",
    kind: "FRICTION",
    text: "有个能力不错的人，总在会议上唱反调。你通常会：",
    options: [
      { key: "A", text: "让他把反对点写成方案，进入流程评审", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "先认可他一部分，再引导他站到队伍里", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "直接控场：反对可以，但要按规则发言/限时", score: [{ agent: "CM", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "D", text: "让他对齐结果：你负责交付，拿结果说话", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
    ],
  },
  {
    id: "Q18",
    scene: "SOC",
    kind: "FRICTION",
    text: "你在表达一个观点时，有人反复打断抢话。你会：",
    options: [
      { key: "A", text: "把节奏夺回来：一句话压住，再继续讲", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "B", text: "顺势把话递给他：让他讲完，然后你总结定调", score: [{ agent: "BR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "不争，转向跟其他人互动，把注意力移开", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "D", text: "私下再聊：当众争执不值，回头再算", score: [{ agent: "TR", weight: 2 }, { agent: "HU", weight: 1 }] },
    ],
  },
  {
    id: "Q19",
    scene: "INT",
    kind: "ACTION",
    text: "你真正想被理解时，你更倾向于：",
    options: [
      { key: "A", text: "把问题讲得很清楚：逻辑、时间线、原因", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "不讲太多，先要一个拥抱/陪伴", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "讲轻松一点，让对方别有压力", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "D", text: "先不说，自己消化完再表达", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
    ],
  },
  {
    id: "Q20",
    scene: "TEAM",
    kind: "ALLOC",
    text: "团队没人领头，你被推到关键位置，你更愿意当：",
    options: [
      { key: "A", text: "规则与节奏的制定者（让系统跑起来）", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "最强执行者（我把最难的做了）", score: [{ agent: "BU", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "C", text: "资源与关系的协调者（把外部搬进来）", score: [{ agent: "TR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "对外发声的人（统一表达、拿下支持）", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
    ],
  },
  {
    id: "Q21",
    scene: "SOC",
    kind: "ACTION",
    text: "你判断一个人值不值得深交，第一信号更可能是：",
    options: [
      { key: "A", text: "他能不能把事说清楚、说到点上", score: [{ agent: "BU", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "B", text: "他对别人有没有分寸、会不会让人舒服", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "他是否有资源/是否靠谱能合作", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "他是否有气场/能否镇得住场", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
    ],
  },
  {
    id: "Q22",
    scene: "INT",
    kind: "FRICTION",
    text: "对方说你太敏感/想太多。你更可能：",
    options: [
      { key: "A", text: "直接解释清楚：我敏感不是无理，是因为某些原因", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "反问一句：那你希望我怎么做？我们对齐一下", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "先止损：我不争对错，我们先暂停，改天再聊", score: [{ agent: "BI", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "轻轻回击：好，那你也别装不在乎", score: [{ agent: "HU", weight: 2 }, { agent: "SI", weight: 1 }] },
    ],
  },
  {
    id: "Q23",
    scene: "TEAM",
    kind: "ACTION",
    text: "你最受不了项目处于哪种状态？",
    options: [
      { key: "A", text: "没有标准、没有流程、全靠感觉", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "谁也不拍板、事情拖着不推进", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "明明机会在，但资源没跟上", score: [{ agent: "TR", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "D", text: "每个人各说各话，对外口径乱", score: [{ agent: "BR", weight: 2 }, { agent: "BI", weight: 1 }] },
    ],
  },
  {
    id: "Q24",
    scene: "SOC",
    kind: "THREAT",
    text: "在一个场合你明显被忽视（没人接话/没人看你），你会：",
    options: [
      { key: "A", text: "提一个有内容的观点，让局面重新聚焦", score: [{ agent: "BR", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "主动倾听、顺势递话，让别人先被看见", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "找到关键人建立连接：一对一先把线拉上", score: [{ agent: "TR", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "D", text: "不勉强，体面退场，把精力留给更值得的局", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q25",
    scene: "TEAM",
    kind: "THREAT",
    text: "客户/上级突然提出不合理要求，且语气强势，团队情绪开始波动。你最可能先：",
    options: [
      { key: "A", text: "把要求拆成可谈的条款：哪些能做、哪些不能做", score: [{ agent: "BU", weight: 2 }, { agent: "TR", weight: 1 }] },
      { key: "B", text: "先稳住对方情绪：别对抗，给一个体面台阶", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "直接划红线：该拒绝就拒绝，否则以后更难控", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "D", text: "先把内部统一：谁对外说什么、谁负责什么", score: [{ agent: "CM", weight: 2 }, { agent: "BR", weight: 1 }] },
    ],
  },
  {
    id: "Q26",
    scene: "INT",
    kind: "THREAT",
    text: "你隐约感觉对方最近有点不一样（更忙/更疏远/话变少），但你没有证据也不确定原因。你更可能先：",
    options: [
      { key: "A", text: "先观察一段时间，看行为趋势再判断", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "用轻松方式切入问一句，看看对方反应", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "C", text: "直接谈边界：我能接受/不能接受的是什么", score: [{ agent: "CM", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "立刻把细节问清楚：到底发生了什么、你在想什么", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q27",
    scene: "SOC",
    kind: "ACTION",
    text: "在一个陌生但高质量的圈子里，你更容易采取的方式是：",
    options: [
      { key: "A", text: "先把场子聊热，让大家舒服，然后再让人记住你", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "B", text: "先精准锁定关键人，建立一条强连接", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "先输出一个硬观点/硬内容，立刻形成标签", score: [{ agent: "BR", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "D", text: "先低调观察：谁是核心、谁是边缘、谁在演", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q28",
    scene: "TEAM",
    kind: "FRICTION",
    text: "团队有个规则能提高效率，但会伤到某个成员的面子。你会：",
    options: [
      { key: "A", text: "规则照上：效率优先，慢慢让大家适应", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "先做一个过渡方案：既保效率，也保体面", score: [{ agent: "SI", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "让成员参与制定：用共识让规则可执行", score: [{ agent: "BI", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "规则暂缓：先把关系稳住，避免内耗", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
    ],
  },
  {
    id: "Q29",
    scene: "INT",
    kind: "ACTION",
    text: "你们吵完架后，你最自然的修复方式是：",
    options: [
      { key: "A", text: "把问题讲清楚：以后怎么避免重复发生", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "主动示好：先把关系抱回来，别让对方冷着", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "给对方空间：等双方都平静了再谈", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "D", text: "做一个实际行动：用做代替说", score: [{ agent: "BU", weight: 2 }, { agent: "TR", weight: 1 }] },
    ],
  },
  {
    id: "Q30",
    scene: "SOC",
    kind: "ALLOC",
    text: "如果你想在一个圈子里更快建立影响力，你更愿意付出的成本是：",
    options: [
      { key: "A", text: "时间：长期稳定出现、持续互动", score: [{ agent: "BI", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "内容：持续输出观点/作品", score: [{ agent: "BR", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "资源：帮别人解决问题、提供机会", score: [{ agent: "TR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "风险：敢说敢站队，形成锋芒", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q31",
    scene: "TEAM",
    kind: "ACTION",
    text: "你主持一个低效会议时，你更可能：",
    options: [
      { key: "A", text: "直接把议程写出来：议题-决策-责任人-截止时间", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "先把大家拉到同一目标上：别争细节先对齐方向", score: [{ agent: "BR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "先找最大阻力点：谁在卡？卡在哪？", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "D", text: "先让关键人表态：谁拍板？谁负责最终决策？", score: [{ agent: "CM", weight: 2 }, { agent: "TR", weight: 1 }] },
    ],
  },
  {
    id: "Q32",
    scene: "INT",
    kind: "FRICTION",
    text: "对方抱怨你像领导一样讲话。你更可能：",
    options: [
      { key: "A", text: "解释：我不是控制你，我是在解决问题", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "调整表达：把话说软一点，但原则不变", score: [{ agent: "SI", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "直接问：那你想要我怎么说？给我一个例子", score: [{ agent: "CM", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "不解释：我先收回节奏，避免继续压迫", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q33",
    scene: "SOC",
    kind: "THREAT",
    text: "有人当众质疑你的资历或能力（不一定恶意）。你会：",
    options: [
      { key: "A", text: "用作品/事实说话：给出一个具体案例", score: [{ agent: "BU", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "B", text: "轻轻带过：不在这种场合证明自己", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "借势反问：你怎么看？让他暴露逻辑", score: [{ agent: "HU", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "D", text: "直接立界限：你可以讨论观点，但别攻击个人", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
    ],
  },
  {
    id: "Q34",
    scene: "TEAM",
    kind: "ALLOC",
    text: "你带团队时，如果只能奖励一个人，你更愿意奖励：",
    options: [
      { key: "A", text: "把最难的扛下来并交付的人", score: [{ agent: "BU", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "B", text: "让团队凝聚、能照顾到每个人的人", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "最能拿资源/拿合作的人", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "在外最能代表团队、让团队被看见的人", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
    ],
  },
  {
    id: "Q35",
    scene: "INT",
    kind: "ACTION",
    text: "你和对方有点僵，但还没彻底翻脸。下面哪一种场景最容易让你突然心软/松动？",
    options: [
      { key: "A", text: "对方给出明确回归时间：我不是不在乎，我X点再找你", score: [{ agent: "CM", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "B", text: "对方拉你一起做一件事：别吵了，我们一起把这件事搞定", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "对方很温柔地靠近你：我想你了，我抱抱你好吗", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "对方主动扛起现实问题：这事我来处理，你别担心", score: [{ agent: "TR", weight: 2 }, { agent: "BU", weight: 1 }] },
    ],
  },
  {
    id: "Q36",
    scene: "SOC",
    kind: "FRICTION",
    text: "有人第一次见面就很热情套近乎，你直觉会：",
    options: [
      { key: "A", text: "顺势互动：先建立连接再说", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "B", text: "保持礼貌但观察：他目的是什么？", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "直接把边界放出来：我们先按规则合作", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "D", text: "看对方能不能带来价值：否则不过度投入", score: [{ agent: "TR", weight: 2 }, { agent: "HU", weight: 1 }] },
    ],
  },
];

// 48题深度版追加：Q37-Q48
export const questionsExtra12: Question[] = [
  {
    id: "Q37",
    scene: "INT",
    kind: "ACTION",
    text: "你准备给对方一个惊喜，但临时发现对方状态一般。你更可能：",
    options: [
      { key: "A", text: "改成一个更容易被接受的小安排，先把体验做舒服", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "B", text: "先问清楚今天的边界：你想独处还是想有人陪", score: [{ agent: "CM", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "把惊喜拆小：能做的就做，不能做的先留到下次", score: [{ agent: "BU", weight: 2 }, { agent: "TR", weight: 1 }] },
      { key: "D", text: "先不推进，观察对方反应和节奏，避免多做多错", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
    ],
  },
  {
    id: "Q38",
    scene: "TEAM",
    kind: "ACTION",
    text: "一个重要环节卡住了，所有人都在等下一步。你更可能先做：",
    options: [
      { key: "A", text: "把卡点写成两条路径：最稳方案与最快三步，立刻试", score: [{ agent: "BU", weight: 2 }, { agent: "TR", weight: 1 }] },
      { key: "B", text: "让关键角色当场表态：谁负责、何时交付、逾期怎么处理", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "C", text: "去外部找补：借资源、借人、借工具，把堵点搬开", score: [{ agent: "TR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "先把对外表达统一：避免信息混乱导致更大成本", score: [{ agent: "BR", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q39",
    scene: "SOC",
    kind: "ACTION",
    text: "你在一个场合需要快速建立信任，你更可能用：",
    options: [
      { key: "A", text: "一个清晰的故事或表达方式，让人迅速懂你是谁", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "B", text: "先把对方照顾好：记住细节、给对方被尊重的感觉", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "用一个小成果或小承诺当场兑现：让信任落地", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "先摸清局里谁关键、谁主导，再选择切入角度", score: [{ agent: "HU", weight: 2 }, { agent: "TR", weight: 1 }] },
    ],
  },
  {
    id: "Q40",
    scene: "INT",
    kind: "THREAT",
    text: "你觉得对方在回避一个问题，但对方表现得很平静。你更可能：",
    options: [
      { key: "A", text: "先把需要被解决的点写成一个具体请求，而不是追问动机", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "给一个可退可进的入口：我不逼你，但我需要一个回来的方式", score: [{ agent: "CM", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "先把氛围拉回舒服：去做点轻松的，等窗口出现再谈", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "D", text: "先收集事实：观察对方行为是否稳定一致，再决定是否升级", score: [{ agent: "HU", weight: 2 }, { agent: "BU", weight: 1 }] },
    ],
  },
  {
    id: "Q41",
    scene: "TEAM",
    kind: "FRICTION",
    text: "有人在群里发了一段带情绪的话，可能引发站队。你更可能：",
    options: [
      { key: "A", text: "立刻把话题拉回事实与任务，给一个清晰的下一步", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "直接定边界：这种表达方式不行，回到规则里说", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "C", text: "先私聊关键人，止血，再决定公开怎么说", score: [{ agent: "TR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "发一段温和但有力量的总结，稳定情绪与共识", score: [{ agent: "BR", weight: 2 }, { agent: "BI", weight: 1 }] },
    ],
  },
  {
    id: "Q42",
    scene: "SOC",
    kind: "THREAT",
    text: "你发现有人在暗中影响别人对你的看法（不一定直接冲突）。你更可能：",
    options: [
      { key: "A", text: "用一个公开可见的成果或事实，让误解自然失效", score: [{ agent: "BU", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "B", text: "找到关键节点沟通：把信息对齐到位，切断扩散", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "C", text: "轻轻把节奏拿回来：用表达与场面重新定义你", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "D", text: "先不动声色，观察是谁在推、推到什么程度，再出手", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q43",
    scene: "INT",
    kind: "ALLOC",
    text: "如果你只能要求对方在重要时刻做到一件事，你更想要：",
    options: [
      { key: "A", text: "明确的回归机制：可以暂停，但必须可回到同一个问题上", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "B", text: "情绪上的靠近：让我感到被放在心上", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "C", text: "可执行的行动：用具体行为兑现承诺", score: [{ agent: "BU", weight: 2 }, { agent: "TR", weight: 1 }] },
      { key: "D", text: "尊重与分寸：别越界、别伤人，保持底线", score: [{ agent: "HU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q44",
    scene: "TEAM",
    kind: "ALLOC",
    text: "你要选一个核心合作者，面对不确定性时，你更看重：",
    options: [
      { key: "A", text: "能把复杂事拆成可执行步骤的人", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "B", text: "能拍板、能设边界、让团队不散的人", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "C", text: "能带来外部支持与路径的人", score: [{ agent: "TR", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "D", text: "能对外表达清楚、让大家愿意跟的人", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
    ],
  },
  {
    id: "Q45",
    scene: "SOC",
    kind: "FRICTION",
    text: "你与一个人观点冲突很大，但你们还得在同一个场合相处。你更可能：",
    options: [
      { key: "A", text: "保持体面与界限：不撕，但也不让步到失控", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "B", text: "用柔和方式缓冲：先让场面舒服，再慢慢调整", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "找一个共同目标或共同利益点，先把合作盘住", score: [{ agent: "TR", weight: 2 }, { agent: "BR", weight: 1 }] },
      { key: "D", text: "把争议写成清晰问题：用事实与标准减少扯皮", score: [{ agent: "BU", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q46",
    scene: "INT",
    kind: "FRICTION",
    text: "当你意识到自己开始上头想控制局面时，你最可能用哪种方式自救",
    options: [
      { key: "A", text: "先延迟：先睡一觉或先停一停，给自己降功耗", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "B", text: "先做动作：把需求变成一个小请求，而不是追问", score: [{ agent: "BU", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "先靠近：先把关系和安全感拿回来再说", score: [{ agent: "BI", weight: 2 }, { agent: "SI", weight: 1 }] },
      { key: "D", text: "先换频道：用轻松方式把紧张解开，让自己松下来", score: [{ agent: "SI", weight: 2 }, { agent: "BR", weight: 1 }] },
    ],
  },
  {
    id: "Q47",
    scene: "TEAM",
    kind: "THREAT",
    text: "你发现一个潜在风险会在后期爆雷，但现在说可能让大家心态崩。你更可能：",
    options: [
      { key: "A", text: "先做一个小实验验证风险大小，再决定怎么说", score: [{ agent: "BU", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "B", text: "先设预案规则：发生X就启动Y，提前写清楚", score: [{ agent: "CM", weight: 2 }, { agent: "BU", weight: 1 }] },
      { key: "C", text: "先去找外部兜底：备用资源或替代方案先拿到手", score: [{ agent: "TR", weight: 2 }, { agent: "CM", weight: 1 }] },
      { key: "D", text: "先统一对外表达：把风险说成可控项，稳住节奏", score: [{ agent: "BR", weight: 2 }, { agent: "CM", weight: 1 }] },
    ],
  },
  {
    id: "Q48",
    scene: "SOC",
    kind: "ALLOC",
    text: "你更容易被哪种人吸引去长期来往（不一定深交）",
    options: [
      { key: "A", text: "做事清爽、能把复杂问题处理得很利落的人", score: [{ agent: "BU", weight: 2 }, { agent: "TR", weight: 1 }] },
      { key: "B", text: "说话有分寸、让人相处舒服、能照顾场面的人", score: [{ agent: "SI", weight: 2 }, { agent: "BI", weight: 1 }] },
      { key: "C", text: "有原则、边界清晰、关键时刻敢站出来的人", score: [{ agent: "CM", weight: 2 }, { agent: "HU", weight: 1 }] },
      { key: "D", text: "表达强、有观点、有记忆点、能带动氛围的人", score: [{ agent: "BR", weight: 2 }, { agent: "SI", weight: 1 }] },
    ],
  },
];
